apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: dhruvrkashyap/frontend
        env:
        - name: REACT_APP_API_URL
          value: "http://af4f790587d414645af49c4561b0ad6b-106430917.ap-south-1.elb.amazonaws.com:3001/api"
        ports:
        - containerPort: 3000

