apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: dhruvrkashyap/frontend:latest
        env:
        - name: REACT_APP_API_URL
          value: "http://34.93.192.146:3001/api"
        ports:
        - containerPort: 3000

