apiVersion: v1
kind: Service
metadata: 
  name: mongo-db
  labels: 
    app: mongo-db
spec: 
  ports: 
    - 
      name: mongodb
      port: 27017
      targetPort: 30332
  type: ClustrerIP
  selector: 
    app: mongo-db
