apiVersion: v1
kind: Service
metadata: 
  name: mongodb
  labels: 
    app: mongodb
spec: 
  ports: 
    - 
      name: mongodb
      port: 27017
      targetPort: 30332
  type: ClusterIP
  selector: 
    app: mongo-db
