  apiVersion: apps/v1
  kind: Deployment
  metadata: 
    name: mongo-db
  spec: 
    selector: 
      matchLabels: 
        app: mongo-db
    replicas: 1
    minReadySeconds: 5
    template: 
      metadata: 
        labels: 
          app: mongo-db
      spec:
        resources:
          requests:
            storage: 1Gi
        containers: 
          - 
            name: mongo-db
            image: mongo
            imagePullPolicy: Always
            env: 
              - 
                name: MONGO_INITDB_ROOT_USERNAME
                value: "dhruv"
                
              -
                name: MONGO_INITDB_ROOT_PASSWORD
                value: "password"
                
            ports: 
              - 
                containerPort: 27017
                name: "mongodb"
