  apiVersion: apps/v1
  kind: Deployment
  metadata: 
    name: mongo
  spec: 
    selector: 
      matchLabels: 
        app: mongo
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: mongo
      spec:
        containers: 
          - 
            name: mongo
            image: mongo
            imagePullPolicy: Always
            env: 
              - 
                name: MONGO_INITDB_ROOT_USERNAME
                value: "dhruv"
                
              -
                name: MONGO_INITDB_ROOT_PASSWORD
                value: "password"
                
            ports: 
              - 
                containerPort: 27017
